<h1> Imports</h1>

In [1]:
import numpy as np
import pandas as pd
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense
from keras.models import load_model
from sklearn.metrics import accuracy_score

In [2]:
df=pd.read_csv('IRIS.csv')
data=df[['sepal_length','sepal_width','petal_length','petal_width']]
target=df['species']

In [3]:
type(target)

pandas.core.series.Series

In [4]:
mapping={'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2}
target=target.map(mapping)

In [6]:
x = data
y = target

In [7]:
y = to_categorical(y)

In [15]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [10]:
scaler_object = MinMaxScaler()
scaler_object.fit(x_train)

MinMaxScaler()

In [11]:
scaled_X_train = scaler_object.transform(x_train)
scaled_X_test = scaler_object.transform(x_test)

In [12]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.fit(scaled_X_train,y_train,epochs=150, verbose=2)

Epoch 1/150
4/4 - 2s - loss: 1.1118 - accuracy: 0.3500 - 2s/epoch - 527ms/step
Epoch 2/150
4/4 - 0s - loss: 1.1089 - accuracy: 0.3500 - 20ms/epoch - 5ms/step
Epoch 3/150
4/4 - 0s - loss: 1.1060 - accuracy: 0.3500 - 34ms/epoch - 9ms/step
Epoch 4/150
4/4 - 0s - loss: 1.1038 - accuracy: 0.3500 - 25ms/epoch - 6ms/step
Epoch 5/150
4/4 - 0s - loss: 1.1011 - accuracy: 0.3500 - 52ms/epoch - 13ms/step
Epoch 6/150
4/4 - 0s - loss: 1.0990 - accuracy: 0.3500 - 21ms/epoch - 5ms/step
Epoch 7/150
4/4 - 0s - loss: 1.0969 - accuracy: 0.3500 - 55ms/epoch - 14ms/step
Epoch 8/150
4/4 - 0s - loss: 1.0949 - accuracy: 0.3400 - 27ms/epoch - 7ms/step
Epoch 9/150
4/4 - 0s - loss: 1.0928 - accuracy: 0.3400 - 48ms/epoch - 12ms/step
Epoch 10/150
4/4 - 0s - loss: 1.0905 - accuracy: 0.3400 - 32ms/epoch - 8ms/step
Epoch 11/150
4/4 - 0s - loss: 1.0883 - accuracy: 0.3400 - 41ms/epoch - 10ms/step
Epoch 12/150
4/4 - 0s - loss: 1.0851 - accuracy: 0.3300 - 37ms/epoch - 9ms/step
Epoch 13/150
4/4 - 0s - loss: 1.0816 - accura

Epoch 103/150
4/4 - 0s - loss: 0.4993 - accuracy: 0.7300 - 37ms/epoch - 9ms/step
Epoch 104/150
4/4 - 0s - loss: 0.4961 - accuracy: 0.7300 - 37ms/epoch - 9ms/step
Epoch 105/150
4/4 - 0s - loss: 0.4919 - accuracy: 0.7300 - 32ms/epoch - 8ms/step
Epoch 106/150
4/4 - 0s - loss: 0.4880 - accuracy: 0.7600 - 35ms/epoch - 9ms/step
Epoch 107/150
4/4 - 0s - loss: 0.4837 - accuracy: 0.8100 - 41ms/epoch - 10ms/step
Epoch 108/150
4/4 - 0s - loss: 0.4785 - accuracy: 0.8200 - 26ms/epoch - 6ms/step
Epoch 109/150
4/4 - 0s - loss: 0.4746 - accuracy: 0.8500 - 39ms/epoch - 10ms/step
Epoch 110/150
4/4 - 0s - loss: 0.4711 - accuracy: 0.9000 - 27ms/epoch - 7ms/step
Epoch 111/150
4/4 - 0s - loss: 0.4672 - accuracy: 0.9000 - 22ms/epoch - 5ms/step
Epoch 112/150
4/4 - 0s - loss: 0.4632 - accuracy: 0.8900 - 41ms/epoch - 10ms/step
Epoch 113/150
4/4 - 0s - loss: 0.4592 - accuracy: 0.8800 - 25ms/epoch - 6ms/step
Epoch 114/150
4/4 - 0s - loss: 0.4555 - accuracy: 0.8800 - 31ms/epoch - 8ms/step
Epoch 115/150
4/4 - 0s - 

In [16]:
#model.predict_classes(scaled_X_test)
predictions=np.argmax(model.predict(scaled_X_test),axis=1)

2/2 [==============================] - 0s 3ms/step


In [17]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [18]:
print(accuracy_score(y_test.argmax(axis=1),predictions))

0.96


In [24]:
model.save('myfirstmodel.h5')

In [19]:
newmodel = load_model('myfirstmodel.h5')

In [20]:
predictions=np.argmax(newmodel.predict(scaled_X_test),axis=1)

2/2 [==============================] - 0s 3ms/step


In [21]:
predictions

array([1, 0, 2, 2, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [23]:
reverse_mapping={0:'Iris-setosa',1:'Iris-versicolor',2:'Iris-virginica'}

In [24]:
classification=[]
for ele in predictions:
    classification.append(reverse_mapping[ele])

In [25]:
print(classification)

['Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica', 'Iris-virginica', 'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica', 'Iris-virginica', 'Iris-versicolor', 'Iris-virginica']
